# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build:
    name: ci_check
    runs-on: ubuntu-latest

    #strategy:
      #matrix:
        #node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Package zip
      run: cd ../ && zip -r webapp.zip webapp && cd - && cp ../webapp.zip .
    - name: Sequilize setup
      run:  export NODE_ENV=development
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.13
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "1.8.3" # or `latest`

    - name: Run `packer init`
      id: init
      run: "packer init ./ami.pkr.hcl"

    - name: Run `packer validate`
      id: validate
      run: "packer validate ./ami.pkr.hcl"
